/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface HorizontalTimeline {
        "points": string[];
        "position": string | number;
    }
    interface MyPlayground {
    }
}
declare global {
    interface HTMLHorizontalTimelineElement extends Components.HorizontalTimeline, HTMLStencilElement {
    }
    var HTMLHorizontalTimelineElement: {
        prototype: HTMLHorizontalTimelineElement;
        new (): HTMLHorizontalTimelineElement;
    };
    interface HTMLMyPlaygroundElement extends Components.MyPlayground, HTMLStencilElement {
    }
    var HTMLMyPlaygroundElement: {
        prototype: HTMLMyPlaygroundElement;
        new (): HTMLMyPlaygroundElement;
    };
    interface HTMLElementTagNameMap {
        "horizontal-timeline": HTMLHorizontalTimelineElement;
        "my-playground": HTMLMyPlaygroundElement;
    }
}
declare namespace LocalJSX {
    interface HorizontalTimeline {
        "points": string[];
        "position"?: string | number;
    }
    interface MyPlayground {
    }
    interface IntrinsicElements {
        "horizontal-timeline": HorizontalTimeline;
        "my-playground": MyPlayground;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "horizontal-timeline": LocalJSX.HorizontalTimeline & JSXBase.HTMLAttributes<HTMLHorizontalTimelineElement>;
            "my-playground": LocalJSX.MyPlayground & JSXBase.HTMLAttributes<HTMLMyPlaygroundElement>;
        }
    }
}
